
/*
 * Please edit me, if you want to modify dram parameter and setting. 2017/05/09
 */
#define AUTOCONF_INCLUDED
#define CONFIG_MIPS_GCC_PATH_PREFIX "/share/rlx/msdk-4.4.7-mips-EB-2.6.19-u0.9.33-m32t-150429/bin/msdk-linux-"
#undef  CONFIG_RTL8676
#undef  CONFIG_RTL8676S
#undef  CONFIG_RTL8685
#undef  CONFIG_RTL8685S
#undef  CONFIG_RTL8685SB
#define CONFIG_RTL8685G 1
#define CONFIG_SOC_NAME "rtl8685g"
#define CONFIG_RTL8685_PERI 1
#undef  CONFIG_RLX
#define CONFIG_MIPS 1

/*
 * Initialization Options
 */
#undef  CONFIG_NAND_FLASH
#define CONFIG_SPI_FLASH 1
#undef  CONFIG_SPI_NAND_FLASH
#undef  CONFIG_NO_FLASH
#define CONFIG_IMAGE_SINGLE 1
#undef  CONFIG_IMAGE_DUAL
#undef  CONFIG_FLASH_2M
#define CONFIG_FLASH_4M 1
#undef  CONFIG_FLASH_16M
#define CONFIG_UART0 1
#undef  CONFIG_UART1
#define CONFIG_FAILRUN_HTTPD 1
#undef  CONFIG_FAILRUN_BOOTP
#undef  CONFIG_FAILRUN_BOOTM
#define CONFIG_SQUASHFS_V4 1
#undef  CONFIG_OSK_APP_SUPPORT
#undef  SUPPORT_MULT_UPGRADE
#undef  CONFIG_OSK_CT_DUAL_IMAGE

/*
 * External Switch Support
 */

/*
 * Frequency configuration
 */
#define CONFIG_SOFTWARE_OVERWRITE_FREQ 1
#undef  CONFIG_SOFTWARE_FREQUENCY_ENV_DECIDE
#undef  CONFIG_OCP0_FREQ_OVER_850
#define CONFIG_SYS_PLL_CTRL 0x001E0E0E
#define CONFIG_MCKG_FREQ_DIV 0x00000000
#define CONFIG_LX_PLL_SEL 0x00000008
#define CONFIG_SYS_CMU_IP_MASK0 0x00000000
#define CONFIG_SYS_CMU_IP_MASK1 0x00000000
#define CONFIG_SYS_CMU_CTRL 0x03ffff00
#define CONFIG_SYS_CMU_SLP_IDX 0x00000000
#undef  CONFIG_RAM_200
#undef  CONFIG_RAM_300
#undef  CONFIG_RAM_350
#undef  CONFIG_RAM_400
#undef  CONFIG_RAM_450
#undef  CONFIG_RAM_500
#undef  CONFIG_RAM_525
#undef  CONFIG_RAM_550
#undef  CONFIG_RAM_600
#undef  CONFIG_RAM_650
#define CONFIG_RAM_MP 1

/*
 * Memory configuration
 */

/*
 * Support DRAM Type
 */
#define CONFIG_DRAM_AUTO_TYPES 1
#define CONFIG_DDR2_USAGE 1
#define CONFIG_DDR3_USAGE 1

/*
 * DRAM Parameters Setting
 */
#define CONFIG_DRAM_AUTO_PARAMETERS 1
#define CONFIG_MEMCTL_TX_DELAY (0)
#define CONFIG_MEMCTL_CLKM_DELAY (0)
#define CONFIG_MEMCTL_CLKM90_DELAY (0)

#undef  CONFIG_HALF_CLK_ENABLE
#define CONFIG_DCACHE_WA_EN 1
#undef  CONFIG_DDR2_DRAM_ODT_VALUE_0
#undef  CONFIG_DDR2_DRAM_ODT_VALUE_50
#define CONFIG_DDR2_DRAM_ODT_VALUE_75 1
#undef  CONFIG_DDR2_DRAM_ODT_VALUE_150
#define CONFIG_DRAM_REDUCE_DRIV_STRENGTH 1
#define CONFIG_DDR3_DRAM_RTT_WR_VALUE_0 1
#undef  CONFIG_DDR3_DRAM_RTT_WR_VALUE_60
#undef  CONFIG_DDR3_DRAM_RTT_WR_VALUE_120
#undef  CONFIG_DDR3_DRAM_RTT_NOM_VALUE_0
#undef  CONFIG_DDR3_DRAM_RTT_NOM_VALUE_40
#define CONFIG_DDR3_DRAM_RTT_NOM_VALUE_60 1
#undef  CONFIG_DDR3_DRAM_RTT_NOM_VALUE_120

//PUPD enable
//#define CONFIG_DRAM_PUPD

//DRAM Capacity Setting
#define CONFIG_DRAM_AUTO_SIZE_DETECTION 1
#undef  CONFIG_ANALOG_DLL_DELAY_LINE
#define CONFIG_TCAS_MAC_PHY
#define CONFIG_DATA_BUF_MASK 1
#define CONFIG_DCACHE_WA_EN 1

//ZQ Calibration
#define CONFIG_ZQ_AUTO_CALI 1

//DRAM Timing Setting
#define CONFIG_DRAM_AUTO_TIMING_SETTING 1
#define CONFIG_DRAM_WR_NS (15)
#define CONFIG_DRAM_RTP_NS (8)
#define CONFIG_DRAM_WTR_NS (9)
#define CONFIG_DRAM_REFI_NS (7800)
#define CONFIG_DRAM_RP_NS (15)
#define CONFIG_DRAM_RCD_NS (15)
#define CONFIG_DRAM_RRD_NS (10)
#define CONFIG_DRAM_FAWG_NS (50)
#define CONFIG_DRAM_RFC_NS (128)
#define CONFIG_DRAM_RAS_NS (45)
#define CONFIG_DDR2_DRAM_ODT_VALUE (75)
#define CONFIG_DDR3_DRAM_RTT_WR_VALUE (0)
#define CONFIG_DDR3_DRAM_RTT_NOM_VALUE (60)
#define CONFIG_PREFERED_DRAM_DRIV_STRENGTH (0)

//Engineer Option
#undef  CONFIG_MAC0_LBK
#undef  CONFIG_GDMA_SCAN
#undef  CONFIG_PCIE_HOST
#define CONFIG_RTL8685_MEMCTL_CHK 1
#undef  CONFIG_NFBI_SLAVE
#undef  CONFIG_RTL8685S_DYNAMIC_FREQ
#undef  CONFIG_BOOT_CMDLINE
#undef  CONFIG_MEM_TEST
#undef  CONFIG_BTG_TEST
#undef  CONFIG_L2C_TEST
#undef  CONFIG_TC2_CNT
